apiVersion: 1

datasources:
  - name: VictoriaLogs-Native
    type: victoriametrics-logs-datasource
    access: proxy
    url: http://victorialogs:9428
    isDefault: false
    editable: true
    jsonData:
      httpMethod: POST
    version: 1
    uid: victorialogs-native-uid
